# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queryparams', models.TextField(verbose_name='Query Params in the API request')),
                ('request_time', models.DateTimeField(auto_now_add=True, verbose_name='Datetime when request was made')),
            ],
            options={
                'verbose_name': 'ApiRequestLogs',
            },
        ),
        migrations.CreateModel(
            name='GithubUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=39, unique=True, verbose_name='Github username')),
                ('user_profile_name', models.CharField(blank=True, max_length=255, verbose_name='Name of the user')),
                ('github_id', models.IntegerField(unique=True, verbose_name='Github ID for the user')),
                ('company', models.CharField(blank=True, max_length=39, verbose_name="Github Username for user's organization")),
                ('avatar_url', models.URLField(blank=True, verbose_name="URL of the user's avatar")),
                ('user_type', models.CharField(choices=[('User', 'User'), ('Organization', 'Organization')], default='User', max_length=12, verbose_name='Type of the user (User/Organization)')),
                ('is_site_admin', models.BooleanField(default=False, verbose_name='Is the  user a site admin?')),
                ('score', models.DecimalField(blank=True, decimal_places=6, max_digits=9, verbose_name='Github score for the user')),
                ('blog', models.URLField(blank=True, verbose_name="Link to user's blog")),
                ('location', models.CharField(max_length=255, verbose_name="User's Location")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name="User's public email")),
                ('available_for_hire', models.BooleanField(default=False, verbose_name='Is the user available for hire?')),
                ('bio', models.TextField(verbose_name='Users Github Bio')),
                ('github_user_created', models.DateTimeField(verbose_name='User created datetime for Github')),
                ('github_user_updated', models.DateTimeField(verbose_name='User updated datetime for Github')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='User created timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='User updated timestamp')),
            ],
            options={
                'verbose_name': 'GithubUserData',
                'verbose_name_plural': 'GithubUsersData',
            },
        ),
    ]
